from enum import Enum

class EnvKeys(Enum):
    OPENSEARCH_PASSWORD = 'OPENSEARCH_INITIAL_ADMIN_PASSWORD'
    OPENSEARCH_USERNAME = 'OPENSEARCH_INITIAL_ADMIN_USERNAME'
    OPENSEARCH_PORT = 'OPENSEARCH_PORT'
    OPENSEARCH_INDEX_NAME = 'OPENSEARCH_INDEX_NAME'
    MONGO_HOST = 'MONGO_HOST'
    MONGO_DB = 'MONGO_DB'
    MONGO_COLLECTION = 'MONGO_COLLECTION'
